### PR TITLE
Check for timeColumn matches partitioned column

### LINKED ISSUE #309: Using the partition column as `timeColumn` results in that column appearing multiple times in the generated WHERE clause
## Bug Report

Using the partition column as `timeColumn` results in that column appearing multiple times in the generated WHERE clause

## Expected Behavior

When the partitioned column is the same as the time column, it only appears once.

```
SELECT
 TIMESTAMP_SECONDS(DIV(UNIX_SECONDS(`start_time`), 2) * 2) AS time,
  avg(`duration`) AS duration
FROM ``
WHERE
  `start_time` BETWEEN TIMESTAMP_MILLIS (1611246930808) AND TIMESTAMP_MILLIS (1611250530808)
GROUP BY 1 
ORDER BY 1 LIMIT 1230"
```

## Actual Behaviour

When using the query builder, this is the result of having the time column as the partitioned column. The expected result would be only including the first clause.

```
SELECT
 TIMESTAMP_SECONDS(DIV(UNIX_SECONDS(`start_time`), 2) * 2) AS time,
  avg(`duration`) AS duration
FROM ``
WHERE
  `start_time` BETWEEN TIMESTAMP_MILLIS (1611246930808) AND TIMESTAMP_MILLIS (1611250530808) AND
  start_time >= '2021-01-21 11:33:56' AND
  start_time < '2021-01-21 12:33:56'
GROUP BY 1 
ORDER BY 1 LIMIT 1230"
```

## Steps to Reproduce the Problem

1. Create a dataset with a `TIMESTAMP` column that is partitioned on that column
2. Use that column as the time column in Grafana

### PR DESCRIPTION
**Pull request by tanner-bruce**
When using the same time column as a partitioned column it results in
having the time column appear twice in the resulting query

**What this PR does / why we need it**:

When appending the partition clause, ensure that it is not the time column.

**Which issue(s) this PR fixes**:

Fixes #309 

**Special notes for your reviewer**:

**Release note**:

```release-note
When using a TIMESTAMP partitioned column, the generated queries will only include a single clause
```

### CODE REVIEW

File: src/bigquery_query.ts [hunk 1]
```diff
@@ -390,21 +390,25 @@ export default class BigQueryQuery {
...
-        const to = `${partitionedField} < '${BigQueryQuery.formatDateToString(
-          this.templateSrv.timeRange.to._d,
-          '-',
-          true
-        )}'`;
-        conditions.push(to);
+      if (this.target.timeColumn !== partitionedField) {
+        if (this.templateSrv.timeRange && this.templateSrv.timeRange.from) {
+          let fromD = this.templateSrv.timeRange.from;
+          const from = `${partitionedField} >= '${BigQueryQuery.formatDateToString(
```
Comment (seuf) [inline src/bigquery_query.ts:396]: I suggest to put the string date in `date()` function.
```
const from = `${partitionedField} >= DATE('${BigQueryQuery.formatDateToString(
              fromD._d,
              '-',
              true
          )}')`;
```
and idem for the `to` condition.. (tested it works fine ;) )

**Review by seuf — CHANGES_REQUESTED** [review]

File: src/bigquery_query.ts (hunk 1 above)
Comment (tanner-bruce) [reply src/bigquery_query.ts:396]: Thanks, I'll 👀 that change once I get a chance

**Comment by ofir5300** [comment]
Hi, your solution looks good.
Please add some tests to your PR and I will approve it.
